# docker-compose for Socorro development.
#
# Note: Requires docker-comopse 1.10+.
version: "2"
services:
    
  postgresql:
    build:
      context: ./docker-postgresql
      dockerfile: ./Dockerfile
    image: kdeyev/pstgrsql
    ports:
      - "5432:5432"
    environment:
      # Create the superuser account
      - POSTGRES_USER=landingnet
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=landingnetdb
#    volumes:
#      - DB: /var/lib/pgsql
      
  # landingnet app
  landingnet:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: kdeyev/landingnet
    depends_on:
      - postgresql
    command: ["./docker/start_landingnet.sh"]
    ports:
      - "5000:5000"
#    volumes:
#      - symbols: /LandingNet/breakpad-debug-symbols
#      - minidumps: /LandingNet/minidumps
  
#volumes:
#  DB:
#  symbols:
#  minidumps: