# Note: Requires docker-comopse 1.10+.
version: "2"
services:
    
  postgresql:
    build:
      context: ./docker-postgresql
      dockerfile: ./Dockerfile
    image: 192.168.203.109:5000/pstgrsql
    ports:
      - "5432:5432"
    environment:
      # Create the superuser account
      - POSTGRES_USER=landingnet
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=landingnetdb
#    volumes:
#      - DB: /var/lib/pgsql
      
  breakpad:
    build:
      context: .
      dockerfile: ./Dockerfile_breakpad
    image: breakpad

  # landingnet app
  crash-collector:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 192.168.203.109:5000/crash-collector
    depends_on:
      - postgresql
      - breakpad
    command: ["./docker/start_landingnet.sh"]
    ports:
      - "5000:5000"
#    volumes:
#      - symbols: /LandingNet/breakpad-debug-symbols
#      - minidumps: /LandingNet/minidumps
  
  elk:
    build:
      context: ./elk-docker
      dockerfile: ./Dockerfile
    image: 192.168.203.109:5000/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      
#volumes:
#  DB:
#  symbols:
#  minidumps: